name: GitHub Actions Demo2
on: 
  push:
    branches:
      - main

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -al
      - run: python3 job.py
      - run: python3 test_moy.py
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker -v
      - run : docker build -t flask_app .
      - run : docker tag flask_app rchristine/ex-devops:latest
      - run : docker login -u rchristine -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - run : docker push rchristine/ex-devops:latest

